# name_or_path: /root/autodl-fs/Llama_3_8b_instruct
# tokenizer_name_or_path: null
# archive: null
# block_name: LlamaDecoderLayer

# policy_dtype: float32
# fsdp_policy_mp: null
# reference_dtype: float16

name_or_path: /root/autodl-fs/pythia-2.8b
tokenizer_name_or_path: null
archive: null
block_name: GPTNeoXLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16